### ISSUE TITLE
"Limited" support of Hamcrest matchers needs explanation

### ISSUE THREAD

**Issue by horenmar** [martinmoene/catch-lest-other-comparison#3]
The reference leads me to Catch's documentation, but it doesn't tell me why the support is considered limited.

**Comment by martinmoene** [comment]
In commit 7b1846be5221ce3fe123a3988ca44a1041265520 I changed the word `limited` to &ndash;the more neutral&ndash; approximate number of matchers in Catch (ca. 10) and added a reference to the [Hamcrest 1.3 Quick Reference (PDF)](http://www.marcphilipp.de/downloads/posts/2013-01-02-hamcrest-quick-reference/Hamcrest-1.3.pdf),which lists in the order of 70 matchers.

Also corrected thelink to the Catch-2 documentation

**Comment by martinmoene** [comment]
Do you think a presentation like the following would improve this aspect of the table?

Feature                           | [doctest](#DOT)| [Catch-1](#CA1)| [Catch-2](#CA2)| [lest](#LST)| Notes |
----------------------------------|:------:|:------:|:------:|:------:|-------|
| Hamcrest matchers (built-in) | - | &#10003; | &#10003; | &bull; | see [12][13][14][15] |
| Hamcrest matchers (user-definable)| - | &#10003; | &#10003; | - | &nbsp; |

**Comment by horenmar** [comment]
My suggestion is for something like this:

**Feature**                           | [doctest](#DOT)| [Catch-1](#CA1)| [Catch-2](#CA2)| [lest](#LST)| Notes |
----------------------------------|:------:|:------:|:------:|:------:|-------|
Hamcrest matchers (built-in)    | - | *some* | *some* | ?? | see [12][13][14][15] |
Hamcrest matchers (user-definable) | - | ✓ | ✓ | ??  | &nbsp;|

**Comment by martinmoene** [comment]
Thanks, done in 5fb591db52ea219fa34e4eb931ba91d02f6d8890
