### ISSUE TITLE
Add reference to Viktor's CppCon17 presentation & slides

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/catch-lest-other-comparison#9]
Viktor's CppCon2017 talk [Mix Tests and Production Code With Doctest - Implementing and Using the Fastest Modern C++ Testing Framework](https://cppcon2017.sched.com/event/BgsI/mix-tests-and-production-code-with-doctest-implementing-and-using-the-fastest-modern-c-testing-framework) provides insight in how doctest (and Catch) work and discusses generally useful techniques.

**Comment by onqtam** [comment]
the talk [is up](https://www.youtube.com/watch?v=eH1CxEC29l8)!

**Comment by martinmoene** [comment]
Thanks, will add it later this week.

**Comment by martinmoene** [comment]
Added in 5cecb90bdfc57f5bfee47047fe32e40d5177b2ca.
